export const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL || "HelveticVault@gmail.com";
export const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";
export const assetPath = (path: string) => `${basePath}${path}`;
const configuredOrigin = process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/+$/, "");
const vercelHost = process.env.VERCEL_PROJECT_PRODUCTION_URL || process.env.VERCEL_URL;
export const siteOrigin = configuredOrigin || (vercelHost ? `https://${vercelHost}` : undefined);
export const socialImage = siteOrigin ? `${siteOrigin}/og.jpg` : assetPath("/og.jpg");
export const siteTitle = "U*TTU Studio — Ton personnage, ta scène, la prise";
export const siteDescription = "Personnage, scène, prise. Tout se fait dans le studio ; le rendu tourne sur ton compte cloud, le studio ne vend rien.";
export const studioTitle = "Studio — U*TTU";
export const studioDescription = "Deux photos, un lieu, une phrase. La prise tourne sur ton compte de rendu et revient dans ton coffre, sur ton appareil. Pas de mur de compte.";
