import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { describe, it } from "node:test";
import manifest from "../src/app/manifest.ts";
import { GUIDE_LINES, nextMoment } from "../src/lib/guide.ts";
import { resumeTab, tabFromLocation } from "../src/lib/studio-route.ts";

const read = (path: string) => readFileSync(path, "utf8");
const catalog = read("messages/fr.json");
const appFiles = readdirSync("src/components/app").filter(name => name.endsWith(".tsx")).map(name => `src/components/app/${name}`);

describe("le studio, une app", () => {
  it("opens on the next gesture and keeps old links working", () => {
    assert.equal(tabFromLocation("", ""), null);
    assert.equal(resumeTab({ lookReady: false, hasScene: true }), "lora");
    assert.equal(resumeTab({ lookReady: true, hasScene: false }), "scene");
    assert.equal(resumeTab({ lookReady: true, hasScene: true }), "prise");
    assert.equal(tabFromLocation("", "?step=look"), "look");
    assert.equal(tabFromLocation("#creer", ""), "look");
    assert.equal(tabFromLocation("#photos", ""), "look");
    assert.equal(tabFromLocation("#plateau", ""), "scene");
    assert.equal(tabFromLocation("#Take", ""), "prise");
    assert.equal(tabFromLocation("#sphère", ""), "sphere");
    assert.equal(tabFromLocation("#fiches", ""), "fiches");
    assert.equal(tabFromLocation("#fiche", ""), "fiches");
    assert.equal(tabFromLocation("#lora", ""), "lora");
    assert.equal(tabFromLocation("#personnage", ""), "lora");
    assert.equal(tabFromLocation("#rôle", ""), "lora");
    assert.equal(tabFromLocation("#Former", ""), "lora");
    assert.equal(tabFromLocation("#compte", ""), "compte");
    assert.equal(tabFromLocation("#inconnu", "?step=prise"), "prise");
    assert.match(read("src/app/studio/page.tsx"), /<StudioApp \/>/);
  });

  it("finishes a take inside the app: no Comfy tab, no Comfy frame as the studio", () => {
    for (const file of appFiles) {
      const text = read(file);
      assert.doesNotMatch(text, /cloud\.comfy\.org|comfy-embed|run_template/, file);
      assert.doesNotMatch(text, /@clerk\//, `${file} stays off Clerk`);
    }
    const context = read("src/components/app/studio-context.tsx");
    assert.match(context, /submitTake\(/);
    assert.match(context, /followTake\(/);
    assert.match(context, /saveInFlight\(localStorage, flight\)/, "a queued take survives a reload");
    assert.ok(context.indexOf("runGate(fresh, claim)") < context.indexOf("submitTake("), "the balance is re-read and gated before anything is sent");
    const sheets = read("src/components/app/sheets.tsx");
    assert.match(sheets, /t\("sheet\.shootRender"\)/);
    assert.match(sheets, /disabled=\{!gate\.allowed\}/);
    assert.ok(catalog.includes("Tourner · débit sur mon compte"));
    const roleFile = read("src/components/app/lora-screen.tsx");
    assert.match(roleFile, /t\("lora\.sendTitle"\)/);
    assert.match(roleFile, /t\("lora\.wontTitle"\)/);
    assert.match(roleFile, /t\("verb\.trainThis"\)/);
    assert.ok(catalog.includes("Ce que tu envoies"));
    assert.ok(catalog.includes("Ce qu’il ne fera pas"));
    assert.ok(catalog.includes("Former ce personnage"));
    assert.match(read("src/components/app/studio-app.tsx"), /LoraScreen/);
    assert.match(context, /submitTraining\(/);
    assert.match(context, /submitLoraTake\(/);
    assert.ok(context.indexOf('falGate(fresh, quote, "formation")') < context.indexOf("submitTraining("), "the training quote is checked before anything is sent");
    assert.ok(context.indexOf('falGate(fresh, quote, "prise")') < context.indexOf("submitLoraTake("), "the take quote is checked before the LoRA is sent");
    assert.match(sheets, /t\("sheet\.trainDebit"\)/);
    assert.ok(catalog.includes("Former · débit sur mon compte fal"));
    assert.doesNotMatch(read("src/components/app/screens.tsx"), /Former ton double/);
    const scene = read("src/components/app/screens.tsx");
    const sceneScreen = scene.slice(scene.indexOf("export function SceneScreen"), scene.indexOf("function clock"));
    assert.match(sceneScreen, /filmAction/);
    assert.match(read("src/lib/render/shot.ts"), /Filmer ce plan/);
    assert.match(read("src/lib/render/take-graph.ts"), /minimax_h3/);
    assert.doesNotMatch(read("src/lib/render/take-graph.ts"), /flux-lora/);
    assert.doesNotMatch(read("src/lib/lora/place.ts"), /reference-to-video\/lora|take-graph/);
    assert.match(read("src/lib/lora/place.ts"), /flux-lora-fast-training/);
    assert.doesNotMatch(sceneScreen, /Préparer la prise|Blender ne tourne pas|Load3DAdvanced|RenderMesh/);
    assert.equal(sceneScreen.match(/u-primary/g)?.length, 1);
    assert.match(sceneScreen, /<details className="u-fold">/);
    assert.match(sceneScreen, /t\("scene\.holdsSummary"\)/);
    assert.match(sceneScreen, /t\("scene\.project"\)/);
    assert.match(sceneScreen, /t\("scene\.noCharacter"\)/);
    assert.match(sceneScreen, /t\("scene\.noTake"\)/);
    assert.ok(catalog.includes("Ce que tient ce lieu"));
    assert.ok(catalog.includes("Aucun personnage sur ce lieu."));
    assert.ok(catalog.includes("Aucune prise pour ce lieu."));
    assert.match(read("src/lib/studio-comfort.ts"), /export function vueProjet/);
    const take = scene.slice(scene.indexOf("export function TakeScreen"), scene.indexOf("export function SphereScreen"));
    assert.match(take, /t\("shelf\.places"\)/);
    assert.doesNotMatch(take, /Décors|Ce décor/);
    assert.match(take, /t\("shelf\.cast"\)/);
    assert.match(take, /className="u-pickers"/);
    assert.doesNotMatch(take, /className="u-plateau"/);
    assert.match(take, /weaveBrief/);
    assert.match(take, /t\("shelf\.noCharacter"\)/);
    assert.match(take, /t\("shelf\.noPlace"\)/);
    assert.match(take, /t\("take\.inSphere"\)/);
    assert.match(read("src/components/app/studio-context.tsx"), /castFile\(current\.loras, loraPick\)/);
    assert.doesNotMatch(take, /Relier mon compte/);
    assert.match(take, /t\("take\.adjust"\)/);
    assert.match(take, /className="u-comfort"/);
    assert.match(take, /t\("take\.engine"\)/);
    assert.match(take, /t\("take\.action"\)/);
    assert.match(take, /t\("take\.format"\)/);
    assert.match(take, /t\("take\.duration"\)/);
    assert.match(take, /className="u-sound"/);
    assert.match(take, /engineMark/);
    assert.equal(take.match(/className="u-primary"/g)?.length, 1);
    assert.doesNotMatch(take, /seedance/i);
    assert.doesNotMatch(take, /className="u-desk"/);
    const chain = read("src/components/app/studio-app.tsx");
    assert.match(chain, /key: "nav.character"/);
    assert.match(chain, /key: "nav.scene"/);
    assert.match(chain, /key: "nav.take"/);
    assert.doesNotMatch(chain, /label: "Look"|label: "Rôle"/);
    assert.match(chain, /t\("nav\.chain"\)/);
    assert.ok(catalog.includes("Personnage, scène, prise"));
    assert.match(chain, /<PlateauShelf /);
    assert.match(chain, /className="u-rail-coffre"/);
    assert.match(read("src/components/app/screens.tsx"), /className="u-plateau"/);
    assert.match(read("src/components/app/screens.tsx"), /t\("shelf\.label"\)/);
    assert.match(read("src/components/app/screens.tsx"), /t\("shelf\.takes"\)/);
    assert.match(chain, /className="u-fiches-nav"/);
    assert.match(chain, /<FichesScreen /);
    assert.equal(chain.match(/\{ id: "(?:lora|scene|prise)", key: "nav\.(?:character|scene|take)" \}/g)?.length, 3);
    const fiches = read("src/components/app/fiches-screen.tsx");
    assert.match(fiches, /t\("fiche\.title"\)/);
    assert.match(fiches, /t\("verb\.lancer"\)/);
    assert.match(fiches, /t\("verb\.relier"\)/);
    assert.ok(catalog.includes("Ce que le studio lance."));
    assert.doesNotMatch(fiches, /u-primary/);
    assert.doesNotMatch(fiches, /seedance|graphe|class_type/i);
    assert.match(chain, /<LookScreen onNext=/);
    assert.match(chain, /onPhotos=/);
    assert.match(chain, /choice=\{choice\}/);
    const role = read("src/components/app/lora-screen.tsx");
    assert.match(role, /t\("lora\.twoWays"\)/);
    assert.ok(catalog.includes("Deux façons."));
    assert.match(role, /className="u-desk u-paths"/);
    assert.match(role, /characterPaths/);
    assert.match(role, /u-secondary/);
    const photos = read("src/components/app/screens.tsx");
    const look = photos.slice(photos.indexOf("export function LookScreen"), photos.indexOf("export function SceneScreen"));
    assert.match(look, /t\("look\.lead"/);
    assert.ok(catalog.includes("Pas de formation."));
    assert.equal(look.match(/u-primary/g)?.length, 1);
    assert.doesNotMatch(chain, /onTrain/);
    assert.match(photos, /t\("look\.reset"\)/);
    assert.match(photos, /t\("scene\.reset"\)/);
    assert.match(photos, /t\("take\.resetPlan"\)/);
    assert.match(role, /t\("lora\.reset"\)/);
    for (const label of ["Remettre ces références", "Remettre ce lieu à zéro", "Remettre cette prise à zéro", "Remettre ce personnage à zéro"]) {
      assert.ok(catalog.includes(label), label);
    }
    const css = read("src/components/app/app.css");
    assert.match(css, /width: min\(560px, 100%\)/);
    assert.match(css, /@media \(min-width: 1080px\)/);
    assert.match(css, /margin-left: 232px/);
    const phone = css.slice(0, css.indexOf("@media (min-width: 720px)"));
    assert.match(phone, /\.u-overlay \{[^}]*align-items: flex-end/);
    assert.match(phone, /\.u-sheet \{[^}]*max-height: 88dvh[^}]*border-radius: 22px 22px 0 0/);
    assert.doesNotMatch(phone, /\.u-sheet \{[^}]*height: 100dvh/);
    assert.match(phone, /\.u-chain \{[^}]*bottom: 0/);
    assert.match(phone, /\.u-plateau \{ display: none; \}/);
    assert.match(phone, /\.u-rail-coffre \{ display: none; \}/);
    assert.doesNotMatch(phone, /width: 232px/);
    const mid = css.slice(css.indexOf("@media (min-width: 720px)"), css.indexOf("@media (min-width: 1080px)"));
    assert.match(mid, /width: min\(720px, 100%\)/);
    assert.doesNotMatch(mid, /width: 232px|margin-left: 232px/);
    const desk = css.slice(css.indexOf("@media (min-width: 1080px)"), css.indexOf("@media (prefers-reduced-motion"));
    assert.match(desk, /width: 232px/);
    assert.match(desk, /\.u-plateau \{[^}]*display: flex/);
    assert.match(desk, /\.u-rail-coffre \{[^}]*display: grid/);
    assert.match(desk, /\.u-top \.u-coffre \{ display: none; \}/);
    assert.match(desk, /margin-right: 300px/);
    assert.match(desk, /\.u-overlay \{[^}]*left: 232px[^}]*right: 300px/);
    assert.doesNotMatch(desk, /height: 100dvh/);
    assert.match(desk, /\.u-comfort-work > \.u-pickers \{ display: none; \}/);
    assert.match(css, /grid-template-columns: minmax\(0, 1fr\) minmax\(320px, 440px\)/);
    assert.match(css, /\.u-paths \{ grid-template-columns: 1fr 1fr; align-items: stretch; \}/);
    assert.match(read("src/components/app/studio-app.tsx"), /aria-label=\{t\("nav\.studio"\)\}><Coffre \/><span>\{t\("nav\.studio"\)\}<\/span>/);
    assert.ok(catalog.includes("Mon studio"));
    assert.match(read("src/app/globals.css"), /\.landing-copy \{ justify-content: space-between; /);
    assert.doesNotMatch(read("src/components/app/lora-screen.tsx"), /@clerk\//);
  });

  it("unbinds each linked account from the sheet the header actually opens", () => {
    const sheets = read("src/components/app/sheets.tsx");
    const credit = sheets.slice(sheets.indexOf("export function CreditSheet"), sheets.indexOf("export function CoffreSheet"));
    assert.match(credit, /t\("sheet\.unlinkRender"\)/);
    assert.match(credit, /t\("sheet\.unlinkFal"\)/);
    assert.ok(credit.indexOf("sheet.unlinkRender") < credit.indexOf("sheet.unlinkFal"), "each account has its own control");
    assert.ok(catalog.includes("Délier le compte de rendu"));
    assert.ok(catalog.includes("Délier le compte fal"));
    assert.match(credit, /connected &&/);
    assert.match(credit, /falLinked &&/);
    const context = read("src/components/app/studio-context.tsx");
    const falOff = context.slice(context.indexOf("const disconnectFal"), context.indexOf("const connectKey"));
    const comfyOff = context.slice(context.indexOf("const disconnect ="), context.indexOf("const exportCoffre"));
    assert.match(falOff, /saveFalKey\(localStorage, null\)/);
    assert.doesNotMatch(falOff, /removeLora|writeLora|coffreZip|deleteDatabase/);
    assert.match(comfyOff, /saveRenderLink\(localStorage, \{ mode: "none" \}\)/);
    assert.match(comfyOff, /tokens\.forget\(\)/);
    assert.doesNotMatch(comfyOff, /removeTake|removeLora|coffreZip|deleteDatabase/);
    const app = read("src/components/app/studio-app.tsx");
    assert.match(app, /className="u-credit" onClick=\{\(\) => setSheet\("credits"\)\}/);
    assert.match(credit, /data-state=\{renderState\}/);
    assert.match(credit, /data-state=\{falState\}/);
    assert.match(credit, /t\("sheet\.walletTitle"\)/);
    assert.match(credit, /t\("verb\.relier"\)/);
    assert.match(credit, /t\("sheet\.quote"\)/);
    assert.doesNotMatch(credit, /strong>\{"—"/);
    assert.ok(catalog.includes("Deux comptes, jamais mélangés"));
    assert.ok(catalog.includes("Aucun chiffre tant que le devis"));
    const coffre = sheets.slice(sheets.indexOf("export function CoffreSheet"), sheets.indexOf("export function ConfirmSheet"));
    assert.match(coffre, /t\("sheet\.studioIntro"\)/);
    assert.match(coffre, /t\("sheet\.export"\)/);
    assert.match(coffre, /t\("sheet\.import"\)/);
    assert.match(coffre, /t\("sheet\.keysOut"\)/);
    assert.match(coffre, /treeFileLabel/);
    for (const line of ["MOC.md", "ouvre ce dossier dans Obsidian", "Exporter mon studio (.zip)", "Importer un studio (.zip)", "Une prise ou un personnage déjà ici reste", "Les clés restent hors de mon studio", "Modèle · Prise"]) {
      assert.ok(catalog.includes(line), line);
    }
    const visible = coffre.slice(coffre.indexOf("return"));
    assert.doesNotMatch(visible, />[^<]*\b[Cc]offre\b[^<]*</);
    assert.doesNotMatch(visible, /"[^"]*\b[Cc]offre\b[^"]*"/);
    assert.doesNotMatch(visible, /"[^"]*\bVault\b[^"]*"/);
    assert.doesNotMatch(coffre, /synchronis/i);
    assert.match(read("src/components/app/studio-context.tsx"), /mergeCoffreZip\(/);
    assert.match(sheets, /t\("sheet\.falPaysTrain"/);
    assert.match(sheets, /t\("sheet\.referencesPays"/);
    assert.ok(catalog.includes("Il paie la formation du personnage"));
    assert.ok(catalog.includes("Il paie les prises"));
  });

  it("publishes from the result, with the file, and never posts by itself", () => {
    const publish = read("src/components/app/publish.tsx");
    assert.match(publish, /navigator\.share\(\{ files: \[/);
    assert.ok(publish.indexOf("async function share()") < publish.indexOf("navigator.share({ files"), "share runs only on the tap");
    assert.match(publish, /xComposerUrl\(caption\)/);
    assert.doesNotMatch(publish, /fetch\("https|api\.x\.com|api\.twitter\.com|upload\.twitter\.com/);
  });

  it("lets U*TTU guide in one short line, with her canon face", () => {
    for (const [moment, line] of Object.entries(GUIDE_LINES)) {
      assert.ok(line.length <= 80, `${moment} stays short`);
      assert.doesNotMatch(line, /\b(comfy|fal|lora|flux|seedance|night city)\b/i, moment);
    }
    const bubble = read("src/components/app/guide-bubble.tsx");
    assert.match(bubble, /\/images\/uttu-canon-portrait\.webp/, "her face comes from the canon portrait");
    assert.equal(nextMoment(["look-photos", "look-name"], { off: false, seen: ["look-photos"] }), "look-name");
    assert.equal(nextMoment(["look-photos"], { off: true, seen: [] }), null);
    assert.equal(nextMoment([false, null, "take-ready"], { off: false, seen: [] }), "take-ready");
  });

  it("installs as an app that opens on the next gesture", () => {
    const app = manifest();
    assert.equal(app.display, "standalone");
    assert.equal(app.start_url, "/studio");
    assert.equal(app.theme_color, "#0B0A09");
  });
});
